# Generated by Django 4.1.1 on 2023-02-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocabulary',
            new_name='Term',
        ),
    ]
