# Generated by Django 4.1.1 on 2023-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_rename_vocabulary_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
