INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (1, 'Bear', 'Oso', 'Animal', 'audio/Bear.mp3', 'Bear.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (2, 'Wolf', 'Lobo', 'Animal', 'audio/Wolf.mp3', 'Wolf.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (3, 'Dog', 'Perro', 'Animal', 'audio/Dog.mp3', 'Dog.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (4, 'Cat', 'Gato', 'Animal', 'audio/Cat.mp3', 'Cat.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (5, 'Horse', 'Caballo', 'Animal', 'audio/Horse.mp3', 'Horse.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (6, 'Rabbit', 'Conejo', 'Animal', 'audio/Rabbit.mp3', 'Rabbit.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (7, 'Sheep', 'Oveja', 'Animal', 'audio/Sheep.mp3', 'Sheep.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (8, 'Cow', 'Vaca', 'Animal', 'audio/Cow.mp3', 'Cow.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (9, 'Goose', 'Ganso', 'Animal', 'audio/Goose.mp3', 'Goose.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (10, 'Chicken', 'Pollo', 'Animal', 'audio/Chicken.mp3', 'Chicken.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (11, 'Pig', 'Cerdo', 'Animal', 'audio/Pig.mp3', 'Pig.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (12, 'Monkey', 'Mono', 'Animal', 'audio/Monkey.mp3', 'Monkey.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (13, 'Fox', 'Zorro', 'Animal', 'audio/Fox.mp3', 'Fox.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (14, 'Panda', 'Panda', 'Animal', 'audio/Panda.mp3', 'Panda.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (15, 'Turtle', 'Tortuga', 'Animal', 'audio/Turtle.mp3', 'Turtle.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (16, 'Spider', 'Araña', 'Animal', 'audio/Spider.mp3', 'Spider.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (17, 'Kangaroo', 'Canguro', 'Animal', 'audio/Kangaroo.mp3', 'Kangaroo.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (18, 'Dolphin', 'Delfín', 'Animal', 'audio/Dolphin.mp3', 'Dolphin.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (19, 'Octopus', 'Pulpo', 'Animal', 'audio/Octopus.mp3', 'Octopus.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (20, 'Crab', 'Cangrejo', 'Animal', 'audio/Crab.mp3', 'Crab.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (21, 'Whale', 'Ballena', 'Animal', 'audio/Whale.mp3', 'Whale.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (22, 'Starfish', 'Estrella de mar', 'Animal', 'audio/Starfish.mp3', 'Starfish.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (23, 'Fish', 'Pez', 'Animal', 'audio/Fish.mp3', 'Fish.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (24, 'Squid', 'Calamar', 'Animal', 'audio/Squid.mp3', 'Squid.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (25, 'Penguin', 'Pingüino', 'Animal', 'audio/Penguin.mp3', 'Penguin.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (26, 'Shark', 'Tiburón', 'Animal', 'audio/Shark.mp3', 'Shark.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (27, 'Jellyfish', 'Medusa', 'Animal', 'audio/Jellyfish.mp3', 'Jellyfish.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (28, 'Bee', 'Abeja', 'Animal', 'audio/Bee.mp3', 'Bee.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (29, 'Fly', 'Mosca', 'Animal', 'audio/Fly.mp3', 'Fly.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (30, 'Butterfly', 'Mariposa', 'Animal', 'audio/Butterfly.mp3', 'Butterfly.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (31, 'Ladybug', 'Mariquita', 'Animal', 'audio/Ladybug.mp3', 'Ladybug.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (32, 'Owl', 'Búho', 'Animal', 'audio/Owl.mp3', 'Owl.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (33, 'Elephant', 'Elefante', 'Animal', 'audio/Elephant.mp3', 'Elephant.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (34, 'Tiger', 'Tigre', 'Animal', 'audio/Tiger.mp3', 'Tiger.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (35, 'Zebra', 'Cebra', 'Animal', 'audio/Zebra.mp3', 'Zebra.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (36, 'Turkey', 'Pavo', 'Animal', 'audio/Turkey.mp3', 'Turkey.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (37, 'Pigeon', 'Paloma', 'Animal', 'audio/Pigeon.mp3', 'Pigeon.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (38, 'Apple', 'Manzana', 'Food', 'audio/Apple.mp3', 'Apple.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (39, 'Banana', 'Plátano', 'Food', 'audio/Banana.mp3', 'Banana.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (40, 'Milk', 'Leche', 'Food', 'audio/Milk.mp3', 'Milk.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (41, 'Bread', 'Pan', 'Food', 'audio/Bread.mp3', 'Bread.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (42, 'Butter', 'Mantequilla', 'Food', 'audio/Butter.mp3', 'Butter.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (43, 'Cheese', 'Queso', 'Food', 'audio/Cheese.mp3', 'Cheese.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (44, 'Yoghurt', 'Yogur', 'Food', 'audio/Yogurt.mp3', 'Yoghurt.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (45, 'Sandwich', 'Sandwich / Bocadillo', 'Food', 'audio/Sandwich.mp3', 'Sandwich.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (46, 'Honey', 'Miel', 'Food', 'audio/Honey.mp3', 'Honey.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (47, 'Salad', 'Ensalada', 'Food', 'audio/Salad.mp3', 'Salad.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (48, 'Egg', 'Huevo', 'Food', 'audio/Egg.mp3', 'Egg.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (49, 'Bacon', 'Panceta', 'Food', 'audio/Bacon.mp3', 'Bacon.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (50, 'Pasta', 'Pasta', 'Food', 'audio/Pasta.mp3', 'Pasta.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (51, 'Cake', 'Tarta', 'Food', 'audio/Cake.mp3', 'Cake.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (52, 'Corn', 'Maíz', 'Food', 'audio/Corn.mp3', 'Corn.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (53, 'Lettuce', 'Lechuga', 'Food', 'audio/Lettuce.mp3', 'Lettuce.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (54, 'Pineapple', 'Piña', 'Food', 'audio/Pineapple.mp3', 'Pineapple.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (55, 'Carrot', 'Zanahoria', 'Food', 'audio/Carrot.mp3', 'Carrot.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (56, 'Tomato', 'Tomate', 'Food', 'audio/Tomato.mp3', 'Tomato.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (57, 'Rice', 'Arroz', 'Food', 'audio/Rice.mp3', 'Rice.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (58, 'Grape', 'Uva', 'Food', 'audio/Grape.mp3', 'Grapes.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (59, 'Orange', 'Naranja', 'Food', 'audio/Orange.mp3', 'Orange.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (60, 'Chips', 'Patatas fritas', 'Food', 'audio/Chip.mp3', 'Chips.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (61, 'Hamburger', 'Hamburguesa', 'Food', 'audio/Hamburger.mp3', 'Hamburger.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (62, 'Sausage', 'Salchicha', 'Food', 'audio/Sausage.mp3', 'Sausages.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (63, 'Juice', 'Zumo', 'Food', 'audio/Juice.mp3', 'Juice.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (64, 'Candy', 'Caramelo / golosina', 'Food', 'audio/Candy.mp3', 'Candy.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (65, 'Water', 'Agua', 'Food', 'audio/Water.mp3', 'Water.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (66, 'Chocolate', 'Chocolate', 'Food', 'audio/Chocolate.mp3', 'Chocolate.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (67, 'Coconut', 'Coco', 'Food', 'audio/Coconut.mp3', 'Coconut.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (68, 'Broccoli', 'Brócoli', 'Food', 'audio/Broccoli.mp3', 'Broccoli.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (69, 'Cauliflower', 'Coliflor', 'Food', 'audio/Cauliflower.mp3', 'Cauliflower.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (70, 'Pepper', 'Pimiento', 'Food', 'audio/Pepper.mp3', 'Pepper.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (71, 'Onion', 'Cebolla', 'Food', 'audio/Onion.mp3', 'Onion.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (72, 'Potato', 'Patata', 'Food', 'audio/Potato.mp3', 'Potato.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (73, 'Armchair', 'Sillón', 'Furniture', 'audio/Armchair.mp3', 'Armchair.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (74, 'Television', 'Televisión', 'Furniture', 'audio/Television.mp3', 'Television.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (75, 'Sofa', 'Sofá', 'Furniture', 'audio/Sofa.mp3', 'Sofa.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (76, 'Chair', 'Silla', 'Furniture', 'audio/Chair.mp3', 'Chair.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (77, 'Table', 'Mesa', 'Furniture', 'audio/Table.mp3', 'Table.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (78, 'Bed', 'Cama', 'Furniture', 'audio/Bed.mp3', 'Bed.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (79, 'Desk', 'Escritorio', 'Furniture', 'audio/Desk.mp3', 'Desk.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (80, 'Wardrobe', 'Armario (para ropa)', 'Furniture', 'audio/Wardrobe.mp3', 'Wardrobe.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (81, 'Bookshelf', 'Estantería de libros', 'Furniture', 'audio/Bookshelf.mp3', 'Bookshelf.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (82, 'Cabinet', 'Armario (para guardar todo tipo de objetos)', 'Furniture', 'audio/Cabinet.mp3', 'Cabinet.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (84, 'Carpet', 'Alfombra', 'Furniture', 'audio/Carpet.mp3', 'Carpet.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (85, 'Cupboard', 'Armario (para cosas de cocina)', 'Furniture', 'audio/Cupboard.mp3', 'Cupboard.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (86, 'Fireplace', 'Chimenea', 'Furniture', 'audio/Fireplace.mp3', 'Fireplace.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (87, 'Curtain', 'Cortina', 'Furniture', 'audio/Curtain.mp3', 'Curtains.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (88, 'Lamp', 'Lámpara', 'Furniture', 'audio/Lamp.mp3', 'Lamp.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (89, 'Telephone', 'Teléfono', 'Furniture', 'audio/Telephone.mp3', 'Telephone.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (90, 'Speaker', 'Altavoz', 'Furniture', 'audio/Speaker.mp3', 'Speaker.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (91, 'Cushion', 'Cojín', 'Furniture', 'audio/Cushion.mp3', 'Cushion.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (92, 'Toilet', 'Retrete', 'Furniture', 'audio/Toilet.mp3', 'Toilet.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (93, 'Clock', 'Reloj', 'Furniture', 'audio/Clock.mp3', 'Clock.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (94, 'Fan', 'Ventilador', 'Furniture', 'audio/Fan.mp3', 'Fan.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (95, 'Shelf', 'Balda', 'Furniture', 'audio/Shelf.mp3', 'Shelf.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (96, 'Candle', 'Vela', 'Furniture', 'audio/Candle.mp3', 'Candles.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (97, 'Mirror', 'Espejo', 'Furniture', 'audio/Mirror.mp3', 'Mirror.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (98, 'Plant', 'Planta', 'Furniture', 'audio/Plant.mp3', 'Plant.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (99, 'Pillow', 'Almohada', 'Furniture', 'audio/Pillow.mp3', 'Pillow.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (100, 'Fridge', 'Frigorífico', 'Furniture', 'audio/Fridge.mp3', 'Fridge.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (101, 'Shower', 'Ducha', 'Furniture', 'audio/Shower.mp3', 'Shower.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (102, 'Bathtub', 'Bañera', 'Furniture', 'audio/Bathtub.mp3', 'Bathtub.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (103, 'Pencil', 'Lápiz', 'School material', 'audio/Pencil.mp3', 'Pencil.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (104, 'Sharpener', 'Sacapuntas', 'School material', 'audio/Sharpener.mp3', 'Sharpener.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (105, 'Rubber', 'Borragoma', 'School material', 'audio/Rubber.mp3', 'Rubber.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (106, 'Ruler', 'Regla', 'School material', 'audio/Ruler.mp3', 'Ruler.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (107, 'Book', 'Libro', 'School material', 'audio/Book.mp3', 'Book.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (108, 'Scissors', 'Tijeras', 'School material', 'audio/Scissors.mp3', 'Scissors.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (109, 'Pen', 'Bolígrafo', 'School material', 'audio/Pen.mp3', 'Pen.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (110, 'Backpack', 'Mochila', 'School material', 'audio/Backpack.mp3', 'Backpack.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (111, 'Glue', 'Pegamento', 'School material', 'audio/Glue.mp3', 'Glue.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (112, 'Crayon', 'Cera', 'School material', 'audio/Crayon.mp3', 'Crayons.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (113, 'Marker', 'Rotulador', 'School material', 'audio/Marker.mp3', 'Marker.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (114, 'Clip', 'Clip', 'School material', 'audio/Clip.mp3', 'Clip.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (115, 'Paper', 'Papel', 'School material', 'audio/Paper.mp3', 'Paper.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (116, 'Notebook', 'Cuaderno', 'School material', 'audio/Notebook.mp3', 'Notebook.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (117, 'Stapler', 'Grapadora', 'School material', 'audio/Stapler.mp3', 'Stapler.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (118, 'Tape', 'Cinta adhesiva', 'School material', 'audio/Tape.mp3', 'Tape.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (119, 'Calculator', 'Calculadora', 'School material', 'audio/Calculator.mp3', 'Calculator.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (120, 'Calendar', 'Calendario', 'School material', 'audio/Calendar.mp3', 'Calendar.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (121, 'Folder', 'Carpeta', 'School material', 'audio/Folder.mp3', 'Folder.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (122, 'Computer', 'Ordenador', 'School material', 'audio/Computer.mp3', 'Computer.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (123, 'Whiteboard', 'Pizarra blanca', 'School material', 'audio/Whiteboard.mp3', 'Whiteboard.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (124, 'Chalk', 'Tiza', 'School material', 'audio/Chalk.mp3', 'Chalk.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (125, 'Highlighter', 'Subrayador', 'School material', 'audio/Highlighter.mp3', 'Highlighter.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (126, 'Paintbrush', 'Pincel', 'School material', 'audio/Paintbrush.mp3', 'Paintbrush.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (127, 'Watercolours', 'Acuarelas', 'School material', 'audio/Watercolours.mp3', 'Watercolors.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (128, 'Blackboard', 'Pizarra', 'School material', 'audio/Blackboard.mp3', 'Blackboard.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (129, 'Printer', 'Impresora', 'School material', 'audio/Printer.mp3', 'Printer.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (130, 'Dictionary', 'Diccionario', 'School material', 'audio/Dictionary.mp3', 'Dictionary.png');
INSERT INTO vocabulary_term (id, word, spanish, types, audio, photo) VALUES (132, 'Globe', 'Globo terráqueo', 'School material', 'audio/Globe.mp3', 'Globe.png');
