# Generated by Django 4.1.1 on 2023-02-17 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_rename_user_appuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Ranking',
        ),
    ]
