# Generated by Django 4.1.1 on 2023-02-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_term_photo'),
        ('user', '0004_ranking_learnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='learnt',
        ),
        migrations.CreateModel(
            name='Learnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ranking')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.term')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='learnts',
            field=models.ManyToManyField(through='user.Learnt', to='vocabulary.term'),
        ),
    ]
