# Generated by Django 4.1.1 on 2023-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_term_photo'),
        ('user', '0005_remove_ranking_learnt_learnt_ranking_learnts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learnt',
            unique_together={('user', 'word')},
        ),
    ]
