# Generated by Django 4.1.1 on 2023-01-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('spanish', models.CharField(max_length=100)),
            ],
        ),
    ]
