# Generated by Django 4.1.1 on 2023-01-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Hangman',
        ),
    ]
