# Generated by Django 4.1.1 on 2023-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hangman_photo_alter_hangman_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
