# Generated by Django 4.1.1 on 2023-02-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_hangman_audio_alter_hangman_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hangman',
        ),
    ]
